name: DevOps Demo Pipeline 3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Build started"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploy started again for test"
